sudo: required
language: node_js
node_js:
  - "14.16.1"

stages:
  - test
  - prod

jobs:
  include:
    - stage: test
      if: NOT(branch=master)
      scripts:
        - npm install
        - npm run test
        - npm install --prefix client
        - npm run test --prefix client
    - stage: prod
      if: branch=master
      deploy:
        skip_cleanup: true
        provider: script
        api_key:
          secure: $HEROKU_API_KEY
        app: allies-art-club-beta
        strategy: git
        