sudo: required
language: node_js
node_js:
  - "14.16.1"

stages:
  - test
  - prod

jobs:
  include:
    - stage: test
      if: NOT(branch=master)
      scripts:
        - npm run test
        - npm run test --prefix client
    - stage: prod
      if: branch=master
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_API_KEY
        