sudo: required

services:
  - docker

stages:
  - name: before_deploy
    if: branch = master
  - name: before_install
    if: branch != master
  - name: scripts
    if: branch != master

before_install:
  - docker build -t harryyy27/allies_art_club/frontend -f ./client/Dockerfile.dev ./client
  - docker build -t harryyy27/allies_art_club/backend -f ./src/Dockerfile.dev ./src
scripts:
  - docker run -e CI=true harryyy27/allies_art_club/frontend npm test
  - docker run -e CI=true harryyy27/allies_art_club/backend npm test


before_deploy:
  - docker build -t harryyy27/allies_art_club/client ./client
  - docker tag harryyy27/allies_art_club/client registry.heroku.com/$HEROKU_APP/client
  - docker build -t harryyy27/allies_art_club/src ./src
  - docker tag harryyy27/allies_art_club/src registry.heroku.com/$HEROKU_APP/src
  - docker build -t harryyy27/allies_art_club/nginx ./nginx
  - docker tag harryyy27/allies_art_club/nginx registry.heroku.com/$HEROKU_APP/nginx
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_API" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
deploy:
  skip_cleanup: true
  provider: script
  script:
    docker ps -a;
    docker push harryyy27/allies_art_club/client;
    docker push registry.heroku.com/$HEROKU_APP/client;
    docker push harryyy27/allies_art_club/src;
    docker push registry.heroku.com/$HEROKU_APP/src;
    docker push harryyy27/allies_art_club/nginx;
    docker push registry.heroku.com/$HEROKU_APP/nginx;
    heroku container:release client src nginx --app $HEROKU_APP;
  on:
    branch: master