version: "3"
services:
  express:
    build:
      dockerfile: Dockerfile.dev
      context: ./src
    volumes:
      - /app/node_modules
      - ./src:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8000:80'
#docker run --name mongodb mongo:3.6.4