"use client"
import React from 'react';
import Header from '../components/header/header.js'
import Footer from '../components/footer/footer.js'
import {Provider} from 'react-redux';
import store from '../utils/store';
import {toggleMenu,toggleSubMenu} from '../utils/Actions/appActions.js';
import GlobalStyle from '../components/Styled/global.styled.js'
import Container from '../components/clipboard/template.js'
import {StyledComponentsRegistry} from '../utils/serverstylesheet.js'
import { bigStem, arialNovaCond,arialNovaCondBold,nickAinley } from './fonts.js';
{/* <head>
<meta charset="utf-8" />
<link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="theme-color" content="#000000" />
<meta
  name="description"
  content="Allie's Art Club is a community organisation developed with the Alexandra Wylie Tower Foundation (AWTF) - a North London charity which supports children, families and vulnerable adults.
  Our aim is to create a culture of community through providing a space where people can connect, collaborate and champion the power of art and creativity."
/>
<meta name="google-site-verification" content="tnHH0A9uBgmEt6WFVhnS74KOLxjNsDaeIXfSvJYNYUE" />
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link rel="stylesheet" type="text/css" media="print" onload="this.onload=null;this.removeAttribute('media');" href="//fonts.googleapis.com/css?family=Architects+Daughter" />
<link rel="stylesheet" href="/assets/fonts/bigstem/stylesheet.css" media="print" onload="this.onload=null;this.removeAttribute('media');"type="text/css" charset="utf-8"/>
<link rel="stylesheet" href="/assets/fonts/nickainley/stylesheet.css" media="print" onload="this.onload=null;this.removeAttribute('media');"type="text/css" charset="utf-8"/>

<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
<title>Allie's Art Club</title>
<style>
  
</style>
  </head> */}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
function RootLayout({ children }) {

  return (
    <Provider store={store}>
    <StyledComponentsRegistry
      
    >
    <html lang="en" className={`${bigStem.variable} ${arialNovaCond.variable} ${arialNovaCondBold.variable} ${nickAinley.variable}`}>
     
      <body>
        
        <GlobalStyle/>
        <Header />
      <p>FUCK YEAHHHH</p>
          <Container>
            {children}   
          </Container>

          <Footer />
      </body>
    </html>
    </StyledComponentsRegistry>
    </Provider>
  );
}
// const mapStateToProps=(state)=>{
//   return {
//       app: state.app,      
//   }
  
// }
// const mapDispatchToProps=(dispatch)=>{
//   return {
//       toggleMenu: (event)=>{
//         toggleMenu(event,dispatch)
//       },
//       toggleSubMenu: (subMenu)=>{
//         toggleSubMenu(subMenu,dispatch)
//       }
      
//   }
// }
// export default connect(mapStateToProps,mapDispatchToProps)(RootLayout);
export default RootLayout;
