sudo: required
language: node_js
node_js:
- 14.16.1
stages:
- test
- prod
jobs:
  include:
  - stage: test
    if: NOT(branch=master)
    scripts:
    - npm install
    - npm run test
    - npm install --prefix client
    - npm run test --prefix client
  - stage: prod
    if: branch=master
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: tDDA/Si2AXZINxZwFTsCDY0zsObYWnnulTYjkdg8BNRf4a7U+Y4LemXCb+ySL/vlSS9SIVSLxItDGaektLNtV7cCDLgouigTOYJmCUwWswIzKwtkgs5TqhVyQWmYgeEQgupU6n7KN3Tx5w1A8ENZbeyqodfXhw3RKU7DVf2Ja2xjeYJyZGSfrsWeG84/0f23UaPxvg6cniBsYIoKweSkkG7UxHmUknhHVGXwk4+x9+NDvBR8Y/KvsFVeGdag7gveIRsU4uU8Oq1ZTMIdz3zobvNo2qeFUCePQLboMGfSicjmRpbkGPraYRvqOnZASDhbA+q1d30aXgWohSKOY/CId9RmdRK2ISFum8yQJMejpHsNPQ7KpAV4ab7NlSvXdWc/LmLvCfhKMoLDR6XsOALIghgdWqPYBJOxC5zXbKNDwCunvB+UrMAA54zWp+lMzLcCrQYv/mnfgWwefopsIuBgZny/+UAt2T5JXR/eLPpW9TtPbmovGVi13O7cV3YWD2EGMHXGIM690GqBMh1uVdsrUXxBEk75AGHwRC8HBl7kvfI9FMkY8XU/ybrJDeV95unrt7/ToNJM7sq6HH3alFQv6nYAavg3J+S2tTSenI8eVhbf3KyqbD3tM8W9Dc3K9G88LnMjgE7cX8Zs+eLDHVSTpvtvN319bPJ/7bh1JDRbpnk=